DATA:
  MEAN:
  - 0.485
  - 0.456
  - 0.406
  STD:
  - 0.229
  - 0.224
  - 0.225
  NUM_WORKERS: 1
  TRAIN:
    DATASETS_NAME:
    - Google_map_with_intersection
    DATASETS_RATIO:
    - 1
    VAL_TRAIN_RATIO: 0.1 
MODEL:
  DCB_DILATION1: 2
  DCB_DILATION2: 4
  TRANSFORMER:
    ENC_LAYERS: 2
    DEC_LAYERS: 2
    DIM_FEEDFORWARD: 2048
    NHEADS: 8
    DROPOUT: 0.1
    PRE_NORM: False
    DIVIDE_NORM: False
TRAIN:
  BATCH_SIZE: 64
  EPOCH: 100
  FREEZE_BACKBONE: True
  LR: 0.0003
  OPTIMIZER: Adam
  WEIGHT_DECAY: 1e-6



